### ISSUE TITLE
Texture Endian Artefacts

### ISSUE THREAD

**Issue by Zenuel** [TheStolenBattenberg/ToolsForKFIV#6]
Some texture files appear to have the wrong endian order applied on conversion resulting in vertical artefacts for some textures, this is especially obvious in **000.map** -> **C2Chest** for textures **chest_0007_0.tx2** and **chest0011_0.tx2**. This issue appears with the Ezee tools build from the release tab so I can't be sure if this is exclusively an issue from a previous build that just hasn't been updated.

![chest_0007_0](https://user-images.githubusercontent.com/4431655/126435588-bd0161dd-23ff-4bd5-a192-b4ee88fa0181.png)
![chest_0011_0](https://user-images.githubusercontent.com/4431655/126435744-ab05dcf8-91b1-49a4-b01b-16d07476eeb5.png)

These tools are invaluable and I'm very grateful for your efforts!

**Comment by TheStolenBattenberg** [comment]
@Zenuel Good to have a name for this finally! Could you clarify if you've found some textures that don't have this artifact? I can fix endian issues quickly if it's for every texture but if it's something in the format it will require a bit more figuring out.

Thanks for you report, I'll take a look into this ASAP. 👍

**Comment by TheStolenBattenberg** [comment]
@Zenuel The issue has been fixed in the new commit, thanks for contributing to the project :)

You'll find a new release in the Releases section which has updated versions of all the tools. I'd recommend switching to using all of these, as there's a load of new improvements to nearly every tool (but specifically the MAPUnpack tool)

**Comment by Zenuel** [comment]
Oh dang! That was super fast, thank you so much!
